### ISSUE TITLE
Turndown Scheduling Build Failure

### ISSUE THREAD

**Issue by CyberC0P** [kubecost/cluster-turndown#40]
Hi guys,

I am trying to use Turndown in a GKE Cluster (v1.22.8-gke.200) but unfortunately on this version I am
experiencing an issue when creating a schedule I see this error......"kubectl create -f example-schedule.yaml
-n turndown error: unable to recognize "example-schedule.yaml": no matches for
 kind "TurndownSchedule"
in version "[kubecost.k8s.io/v1alpha1](http://kubecost.k8s.io/v1alpha1)"

This has worked for me in lower versions previously!

Thanks for your help.

Cheers,
John

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/1429

Addresses this-- we'll want to get this repo up-to-date as well!

**Comment by michaelmdresser** [comment]
Hi @CyberC0P, thanks for the report. I've opened a PR to fix this issue here: https://github.com/kubecost/cluster-turndown/pull/44. Once that's been merged, I'll cut a new release of cluster-turndown and let you know here.

**Comment by michaelmdresser** [comment]
Hi @CyberC0P we've addressed this issue in v2.0.0 of cluster-turndown. You can find the latest releases here: https://github.com/kubecost/cluster-turndown/releases.

Unfortunately, as you'll see in the release notes, this fix necessitated breaking changes to the turndown CRDs. This shouldn't affect new deployments of cluster-turndown that start at v2.0.0.

I'm closing this issue because it should be resolved. If v2.0.0 of cluster-controller does not address your issue, please feel free to reopen!

**Comment by michaelmdresser** [comment]
Just a heads up, we're going to try adding migration of existing `turndownschedules.kubecost.k8s.io` resources to `turndownschedules.kubecost.com` in an upcoming release of turndown, if you'd like to wait for that.
